accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from . import views

urlpatterns = [
    url(r'^login/$', login, name='login'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^logout/$', logout, name='logout'),
]

askdjango/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^$', lambda request: redirect('/blog/')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>\d+)/$', views.category_detail, name='category_detail'),
    url(r'^(?P<category_pk>\d+)/comments/new$', views.review_new, name='review_new'),
    url(r'^(?P<category_pk>\d+)/comments/(?P<pk>\d+)/edit/$', views.review_edit, name='review_edit'),
]

accounts/models.py
from django.db import models

blog/models.py
from django.conf import settings
from django.db import models

class Category(models.Model):
    title = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class Shop(models.Model):
    post_shop = models.ForeignKey(Category)
    title = models.CharField(max_length=100)
    content_phone = models.CharField(max_length=100)
    content_adress = models.CharField(max_length=100)
    content_detail = models.TextField()
    photo = models.ImageField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Review(models.Model):
    post_review = models.ForeignKey(Shop)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

blog/forms.py
from django import forms
from .models import Review

class CommentForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['message']

accounts/views.py
from django.shortcuts import redirect, render
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm
from blog import views

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog:index')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup_form.html',{
        'form': form,
        })

blog/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Shop, Review
from .forms import CommentForm

def index(request):
    shop_list = Category.objects.all()
    return render(request, 'blog/index.html', {
        'shop_list': shop_list,
        })

def category_detail(request, pk):
    category = get_object_or_404(Category, pk=pk)
    return render(request, 'blog/category.html', {
        'category': category,
        })

def category_new(request, category_pk):
    pass

def category_edit(request, category_pk, pk):
    pass

def shop_detail(request, pk):
    pass

def shop_new(request, category_pk):
    pass

def shop_edit(request, category_pk, pk):
    pass

def review_new(request, category_pk):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = get_object_or_404(Category, pk=category_pk)
            comment.user = request.user
            comment.save()
            messages.success(request, '새로운 리뷰가 생성되었습니다.')
            return redirect('blog:category_detail', category_pk)
    else:
        form = CommentForm()
    return render(request, 'blog/category.html')

def review_edit(request, category_pk, pk):
    comment = get_object_or_404(Category, pk=pk)

    if request.method == 'POST':
        form = CommentForm(request,POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = get_object_or_404(Category, pk=category_pk)
            comment.user = request.user
            comment.save()
            messages.success(request, '리뷰가 수정되었습니다.')
            return redirect('blog:category_detail', category_pk)
    else:
        form = CommentForm(instance=comment)
    return render(request, 'blog/category.html', {'form': form})

accounts/templates/accounts/signup_form.html
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" />
</form>

blog/templates/blog/base.html
<!doctype html>
<html>
<head>
<meta charset="utf8" />
<title>Blog</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
<style>
body {
    padding-top: 60px;
    padding-bottom: 30px;
}
</style>
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">FINAL</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a href="{% url "logout" %}?next={{ request.path }}">로그아웃</a></li>
            {% else %}
              <li><a href="{% url "login" %}?next={{ request.path }}">로그인</a></li>
              <li><a href="{% url "signup" %}">회원가입</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-sm-12">

                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}

                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

blog/templates/blog/category.html
<h1>{{ category.title }}</h1>

{{ category.created_at }}
{{ category.updated_at }}
<hr/>

<img src="{{category.photo.url}}" />

{{ category.content|linebreaks }}

{% extends "blog/base.html" %}

{% block content %}
    <h1>{{ category.title }}</h1>

    {{ category.created_at }}
    {{ category.updated_at }}
    <hr/>

    <img src="{{ category.photo.url }}" />

    {{ category.content|linebreaks }}

    <h3>댓글</h3>
    <a href="{% url "blog:comment_new" category.pk %}" class="btn btn-primary btn-block">댓글 쓰기</a>
    <ul>
    {% for comment in category.comment_set.all %}
    <li>
        {{ comment.message }}
        by {{ comment.user }}
        {{ comment.created_at }}
        <a href="{% url "blog:review_edit" category.pk comment.pk %}">
            수정
        </a>
    </li>
    {% endfor %}
    </ul>

    <hr/>
    <a href="{% url "blog:index" %}" class="btn btn-default">글 목록</a>
{% endblock %}

blog/templates/blog/index.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="row">
        {% for shop in shop_list %}
        <div class="col-sm-4">
            <img src="{{ post.photo.url }}" style="max-width: 100%;" />
            <div class="caption">
                <a href="{% url "blog:category_detail" post.pk %}">
                    {{ category.title }}
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}